### ISSUE TITLE
Financiero004 - Estado Cartera

### ISSUE THREAD

**Issue by alejosg1285** [QuestCali/QuestComercial#142]

**Comment by alejosg1285** [comment]
Cambio de origen de la condición de pago, de Cartera.TipoPago a Cliente.CondicionPago

**Comment by balthierStar** [comment]
Rediseñar Reporte, @dtrochezs Se envía el reporte al nuevo repositorio

**Comment by balthierStar** [comment]
Issue moved to [QuestCali/Q-Ana #2](https://github.com/QuestCali/Q-Ana/issues/2) via [**ZenHub**](https://www.zenhub.com/)
